baseURL = 'https://imdrone.co.kr'
languageCode = 'en-us'
#paginate = 6
pagination.pagerSize = 6
theme= "coHub"
title = '아이엠드론'
 

  # Main Menu
  [[menu.Main]]
  name = "홈"
  url= ""
  weight = 1
  [[menu.Main]]
  name = "서비스"
  url= "#gallery"
  weight = 2
  [[menu.Main]]
  name = "소개"
  url= "/about/"
  weight = 3
  [[menu.Main]]
  name = "포트폴리오"
  url= "/blog/"
  weight = 4
  [[menu.Main]]
  name = "FAQ"
  url= "#faq"
  weight = 5


  # Sitemap Menu
  [[menu.sitemap]]
  name = "Privacy Policy"
  url = "/privacy/"
  weight = 1
  [[menu.sitemap]]
  name = "Terms"
  url = "/terms/"
  weight = 2

[params]
  # theme_overrides = "css/overrides.css"
  aboutPageURL = "blog"
  contactLink = "contact"
  copyright = "© {year} <a href=\"https://imdrone.co.kr/\" target=\"_blank\">아이엠드론 </a>"
  fabFormURL =  "https://fabform.io/f/u00kv3-"
  googleAnalytics = "G-JZ95FEWF9K"
  logo = "images/logo-new.png"
  footerlogo = "images/logo-new.png"
  footerDescription = "다양한 산업에 맞춘 혁신적인 드론 서비스로 고객의 성공적인 프로젝트를 함께 만들어 갑니다."

  [params.address]
  address = "죽림중앙로 7-39 506호 <br>  전라남도 여수시"
  email = "imdrone.site@gmail.com"
  openingDesc = "언제든지 전화 주시거나 방문해 주세요. 평일 영업일 내에 모든 문의에 신속하게 답변드립니다."
  openingHours = "9:00 - 18:00"
  phone = "010-4790-6650"

  [params.map]
  APIkey = "AIzaSyC9rV6yesIygoVKTD6QLf_iCa9eiIIHqZ0"
  latitude = "45.4502528"
  longitude = "-122.783407"
  pinImage = "images/pin.png"

  # Social icons
  [[params.social]]
  icon = "ti-youtube"
  url = "https://www.youtube.com/@imdrone6824/"
    [[params.social]]
  icon = "ti-instagram"
  url = "https://www.instagram.com/imdrone_official"
  weight = 1
